bbs/urls.py
from django.urls import path
from . import views

app_name    = "bbs"
urlpatterns = [
    path('', views.index, name="index"),
    path('edit/<int:pk>/', views.edit, name="edit"),
    path('delete/<int:pk>/', views.delete, name="delete"),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("bbs.urls")),
]

bbs/models.py
from django.db import models
from django.utils import timezone

class Topic(models.Model):

    class Meta:
        db_table = "topic"

    name        = models.CharField(verbose_name="投稿者の名前",max_length=100)
    comment     = models.CharField(verbose_name="コメント",max_length=2000)
    dt          = models.DateTimeField(verbose_name="投稿日時",default=timezone.now)

    def __str__(self):
        return self.comment

bbs/forms.py
from django import forms 

from .models import Topic

class TopicForm(forms.ModelForm):

    class Meta:
        model   = Topic
        fields  = [ "comment","name" ]

bbs/views.py
from django.shortcuts import render,redirect
from django.views import View
from django.db.models import Q

from .models import Topic
from .forms import TopicForm

import datetime

class BbsView(View):

    def get(self, request, *args, **kwargs):

        #topics  = Topic.objects.all().order_by("-dt")
        #topics  = Topic.objects.all().order_by("name")
        
        #filterで条件を指定して絞り込みができる。
        #topics  = Topic.objects.filter(id=10).order_by("-dt")
        #topics  = Topic.objects.filter(name="AAA").order_by("-dt")

        """
        topics = [ {"id": "1", "comment": "あああああ"},
                   {"id": "2", "comment": "こんにちは"},
                   {"id": "3", "comment": "Hello"},
                   {"id": "4", "comment": "あああ"},
                   ]
        """

        if "search" in request.GET:
            #(1)キーワードが空欄もしくはスペースのみの場合、ページにリダイレクト
            if request.GET["search"] == "" or request.GET["search"].isspace():
                return redirect("bbs:index")

            #(2)キーワードをリスト化させる(複数指定の場合に対応させるため)
            search      = request.GET["search"].replace("　"," ")
            search_list = search.split(" ")

            #(3)クエリを作る
            query       = Q()
            for word in search_list:

                #空欄の場合は次のループへ
                if word == "":
                    continue

                #TIPS:AND検索の場合は&を、OR検索の場合は|を使用する。
                query &= Q(comment__contains=word)

            #(4)作ったクエリを実行
            topics  = Topic.objects.filter(query).order_by("-dt")
        else:
            topics  = Topic.objects.all().order_by("-dt")

        context = { "topics":topics }

        return render(request,"bbs/index.html",context)

    def post(self, request, *args, **kwargs):

        form    = TopicForm(request.POST)

        if form.is_valid():
            print("バリデーションOK")
            form.save()
        else:
            print("バリデーションNG")


        """
        if "comment" in request.POST:
            print(request.POST["comment"])

            posted  = Topic( comment=request.POST["comment"] )
            posted.save()

        else:
            print("commentがありません")
        """

        #POST文は基本的にredirectをreturnする。
        #"app_name:name"の文字列を
        #return render(request, "bbs/index.html")
        return redirect("bbs:index")

index   = BbsView.as_view()


class BbsEditView(View):
    
    def get(self, request, pk, *args, **kwargs):

        topic   = Topic.objects.filter(id=pk).first()
        context = { "topic":topic }

        return render(request, "bbs/edit.html", context)

    def post(self, request, pk, *args, **kwargs):

        #対象のトピックを特定
        topic   = Topic.objects.filter(id=pk).first()

        #instanceに特定したトピックを指定、これで編集ができる。
        form    = TopicForm(request.POST,instance=topic)
        
        if form.is_valid():
            print("バリデーションOK")
            form.save()

        return redirect("bbs:index")

edit    = BbsEditView.as_view()


class BbsDeleteView(View):

    def post(self, request, pk, *args, **kwargs):

        #対象のトピックを特定して削除する。
        topic   = Topic.objects.filter(id=pk).first()
        topic.delete()

        return redirect("bbs:index")

delete  = BbsDeleteView.as_view()

templates/bbs/edit.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

</head>
<body>

    <h1>編集フォーム</h1>

    <form action="{% url 'bbs:edit' topic.id  %}" method="POST">
        {% csrf_token %}
        <input class="form-control my-1" type="text" name="name" placeholder="名前" value="{{ topic.name }}">
        <textarea class="form-control my-1" name="comment" placeholder="コメント">{{ topic.comment }}</textarea>
        <input type="submit" value="編集">
    </form>

</body>
</html>

templates/bbs/index.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

</head>
<body>
    <h1>HELLO WORLD!!</h1>

    <form action="" method="GET">
        <input type="text" name="search">
        <input type="submit" value="検索">
    </form>

    <form action="" method="POST">
        {% csrf_token %}
        <input class="form-control my-1" type="text" name="name" placeholder="名前">
        <textarea class="form-control my-1" name="comment" placeholder="コメント"></textarea>
        <input type="submit" value="POST文送信">
    </form>

    {% for topic in topics %}
    <div>{{ topic }}</div>
    {% endfor %}

    {% for topic in topics %}
    <div class="border my-2 p-1">
        <div>id:{{ topic.id }}</div>
        <div>投稿日時:{{ topic.dt|date:"Y年m月d日 H時i分s秒" }}</div>
        <div>名前:{{ topic.name }}</div>
        <div>コメント:{{ topic.comment }}</div>
        
        <a class="btn btn-success" href="{% url 'bbs:edit' topic.id %}">編集</a>
        <form action="{% url 'bbs:delete' topic.id  %}" method="POST" style="display:inline-block;">
            {% csrf_token %}
            <button class="btn btn-danger">削除</button>
        </form>

    </div>
    {% endfor %}

    <div>{{ topics|length }}件の投稿があります。</div>

</body>

</html>